src/InspectorContainer.tsx, src/classes/GraphClass.ts, src/components/FloatingNodeMenu.tsx, src/utils/style.module.css
=> Moved node source to floating menu

src/nodes/base.ts, src/nodes/data/array.tsx, src/nodes/data/dataFunctions.tsx, src/nodes/data/json.tsx, src/nodes/draw.tsx, src/utils/constants.tsx, src/widgets.tsx
This PR is in preparation of our Twitter demo
* PIXIContainer
* Built in an option to add a custom click event
* Added output for last clicked index - clickedTargetIndex
* Added output array of which ones were clicked - clickedTargetArray
* Add option for PIXIText to set align
* Fixed issues when inputing string numbers into PIXI nodes
* Added an Array length node
* Some other small fixes
Here an example graph
[Tweet filter example v01 - 2021-11-18 at 22.28.54.ppgraph.zip](https://github.com/fakob/plug-and-play/files/7566136/Tweet.filter.example.v01.-.2021-11-18.at.22.28.54.ppgraph.zip)
=> Custom click event

src/nodes/base.ts, src/nodes/data/array.tsx, src/utils/utils.ts, src/widgets.tsx
* Updated and renamed TimeAndDate node using an enum generated from actual Date class
* Added a general Array methods node using an enum generated from the Array class
=> Updated TimeAndDate node and added a general Array methods node

src/classes/GraphClass.ts, src/classes/LinkClass.ts, src/classes/NodeClass.ts
biggest difference is when loading a graph
=> Performance stability improvements

package.json, src/App.tsx, src/InspectorContainer.tsx, src/PropertyArrayContainer.tsx, src/classes/GraphClass.ts, src/classes/SelectionClass.ts, src/components/ContextMenus.tsx, src/components/FloatingNodeMenu.tsx, src/components/Search.tsx, src/custom.d.ts, src/nodes/datatypes/abstractType.tsx, src/utils/customTheme.ts, src/utils/global.css, src/utils/interfaces.tsx, src/utils/style.module.css, src/widgets.tsx, yarn.lock
I have now moved almost everything from blueprintjs to mui. The one thing missing is the Table node.
I changed the styling a bit, but am still struggling with getting the graph search on top update after editing the name or deleting a graph.
I have also removed dat.gui which was not used anymore and list under the security issues.
=> Switch from blueprintjs to mui

src/nodes/draw2.tsx
Small fix for the text. The width parameter would scale the text, the one we had before is wordWrapWidth in style.
=> Fix text width

package.json, src/App.tsx, src/index.tsx, src/nodes/text.tsx, src/utils/style.module.css, yarn.lock
I have
* added snackbar package
* added some messaging
* removed automatic saving of remote file with an option to save it or dismiss it
* fixed an issue with the label node
Btw, the only change in App.tsx below line 1132 was that I moved ThemeProvider and SnackbarProvider into index.tsx.
=> Added snackbar package and removed automatic saving of remote file

src/nodes/data/json.tsx, src/utils/utils.ts
* Added a json set node, where you can set a new value on a given json path
* Added name and descriptions for the existing JSON nodes
* [Breaking change] Update the path socket name
=> Json set node

src/classes/NodeClass.ts
Reverting this small change here:
https://github.com/fakob/plug-and-play/commit/f4dda942e1152f4eb8aa0522c5b5181671965ba0#r68035206
=> Fixing floating sockets

package.json, src/components/JsonPathPicker.tsx, src/nodes/data/json.tsx, src/utils/utils.ts, src/widgets.tsx, yarn.lock
* added the JSON5 package as it is more lenient when it comes to JSON parsing
* unified the JSON parsing in a function catering for both strings and objects as inputs
=> More lenient json handling

src/nodes/data/dataFunctions.tsx, src/nodes/datatypes/arrayType.tsx, src/nodes/datatypes/colorType.tsx, src/nodes/datatypes/jsonType.tsx, src/nodes/draw.tsx
now inputted per node more like how it used to be
=> better node data handling

src/App.tsx, src/classes/GraphClass.ts, src/utils/interfaces.tsx, src/utils/utils.ts
Added copy paste functionality
=> Copy paste nodes

src/App.tsx
This fixes an issue where deleting the current graph would lead to an undefined state
And the fallback graph is now the last saved graph
=> Fixed issue when deleting the current graph

package.json, src/App.tsx, src/classes/GraphClass.ts, src/classes/NodeClass.ts, src/classes/SelectionClass.ts, src/nodes/image/image.ts, src/nodes/table.tsx, src/utils/global.css, src/utils/style.module.css, src/utils/utils.ts, src/utils/xlsxspread.ts, yarn.lock
As the old table node was never working properly I have now redone it completely. 
The format handling is done using: https://github.com/SheetJS/sheetjs
The spreadsheet editor is done using: https://github.com/myliang/x-spreadsheet. This package was the best one I found, but it has some flaws. Let's see how far we get.
The table node has the following features: 
* Import (drag and drop) of a lot of spreadsheet formats
* Create empty spreadsheet and copy paste data in
* Support for multiple sheets including create/rename/delete
* Support for copy/paste
* Support for adding/removing lines
* Support for editing values
* Outputs
* the whole workbook - native format
* the selected worksheet
* native format
* json (header is used as keys)
* array of arrays
* csv
Known limitations:
* If you want …
=> Redone table node

src/App.tsx, src/classes/NodeClass.ts, src/components/ContextMenus.tsx, src/utils/constants.tsx, src/utils/interfaces.tsx, src/utils/utils.ts
I have now added a gesture mode. By default it is set to auto-detect the pointer device. In case it detects a mouse/scroll-wheel it sets the scroll wheel to be zoom. This detection happens if you have not manually set to mouse or trackpad mode and happens only on loading.
The mode can be set in the context menu.
=> Fix scroll wheel behaviour

package.json, src/classes/GraphClass.ts, src/classes/NodeClass.ts, src/nodes/base.ts, src/nodes/data/json.tsx, src/nodes/draw.tsx, src/utils/constants.tsx, src/utils/inputParser.ts, src/utils/utils.ts, src/widgets.tsx, yarn.lock
I have now broken out some stuff from the preset PR so we can already make use of it.
* Added the following nodes
* keyboard
* if then
* compare
* isValid
* added a pointer down output to the multiplier node
=> Useful nodes

src/PropertyArrayContainer.tsx, src/classes/GraphClass.ts, src/classes/LinkClass.ts, src/classes/NodeClass.ts, src/classes/SocketClass.ts, src/utils/interfaces.tsx
clean attempt at some of the things i tried before, breaks backward compatibility
=> Node refactor 2

src/classes/NodeClass.ts, src/classes/UpdateBehaviourClass.ts, src/components/FloatingNodeMenu.tsx, src/nodes/api/get.tsx, src/nodes/api/pixotopeGateway.tsx, src/nodes/image/shader.ts, src/utils/constants.tsx, src/utils/interfaces.tsx
This PR should visualise the update behaviour for each node in a simple way. Even though this is not perfect, I think it is a good first step.
A small element on the top of every node
* shows the update behaviour
* if update is selected -> nothing is shown (as this is the default setting)
* if update is not selected -> a square is shown (sort of like a stop sign)
* if interval is selected -> the interval frequency is shown
* allows to update now
* when hovering over a node -> a circle button is shown, clicking it does the same as "update now"
=> Update behaviour header

src/App.tsx, src/classes/GraphClass.ts, src/classes/SocketClass.ts, src/components/ContextMenus.tsx, src/components/FloatingNodeMenu.tsx, src/nodes/base.ts, src/nodes/data/array.tsx, src/nodes/datatypes/abstractType.tsx, src/nodes/datatypes/booleanType.tsx, src/nodes/datatypes/numberType.tsx, src/nodes/datatypes/triggerType.tsx, src/nodes/logViewer.tsx, src/nodes/table.tsx, src/nodes/text.tsx
I added
* the ability to right click on the socket name
* for inputs, allow connecting widget nodes
* for outputs allow to connect a label node 
* added a delete socket action for none default sockets
* I have updated all nodes to use `getDefaultIO` for socket creation
https://user-images.githubusercontent.com/4619772/171721168-19866101-9ec2-4439-8894-c0a2308f10dd.mp4
=> Create widget from socket

src/App.tsx, src/classes/NodeClass.ts, src/classes/SocketClass.ts, src/nodes/allNodes.ts, src/nodes/base.ts, src/nodes/data/array.tsx, src/nodes/data/dataFunctions.tsx, src/nodes/data/json.tsx, src/nodes/draw/draw.tsx, src/nodes/image/image.ts, src/nodes/image/shader.ts, src/nodes/logViewer.tsx, src/nodes/macro/macro.ts, src/nodes/math.ts, src/nodes/table.tsx, src/nodes/text.tsx, src/nodes/utility/utility.ts, src/utils/interfaces.tsx
looks very ugly but needs some other changes to make it look good
=> Reroute node

src/App.tsx, src/classes/GraphClass.ts
Fixed the node insert position when dragging a link. 
* Drag link from socket
* Mouse up where the node should be inserted - Link stays there
* Select node from nodeselection - Node is inserted on the above location
=> Fix node insert position

src/nodes/widgets/widgetNodes.tsx
This fixes the issue that the initial values were not actually sent on startup.
=> Fix widget nodes initial value sending

src/App.tsx, src/classes/GraphClass.ts, src/classes/NodeClass.ts, src/components/ContextMenus.tsx, src/nodes/draw/draw.tsx, src/utils/constants.tsx, src/utils/interfaces.tsx
* Added support for switching column and row order for multiply node
* Added support for turning of execution visualisation
=> Switching column and row order and execution visualisation

package.json, server.js, src/App.tsx, yarn.lock
Otherwise we get a CORS error when running locally. Or is there a better way of doing this?
=> Added check for localhost

src/PropertyArrayContainer.tsx, src/classes/GraphClass.ts, src/nodes/datatypes/abstractType.tsx, src/nodes/datatypes/codeType.tsx, src/nodes/datatypes/triggerType.tsx, src/nodes/draw/draw.tsx
* Added option to add/browse nodes when dragging a connection from an input. Same as when dragging an output connection.
* Added the CodeEditor node as defaultInputNodeWidget for codeType
* Changed injected data default to []
* Removed triggerType from output type list
=> Some small improvements

babel.config.js, package.json, src/classes/NodeClass.ts, tsconfig.json, webpack.config.ts, webpack.production.ts, yarn.lock
I have done some changes and it has gotten a bit smaller, but I am unsure if tree shaking is properly working. I just don't know.
Forgot to mention. We lost around 500kb
=> Get tree shaking to work

src/index.tsx
This should fix the render issue.
=> Fix render issue when react elements extend outside the visible area

src/App.tsx, src/classes/GraphClass.ts, src/classes/HybridNode.ts, src/classes/NodeClass.ts, src/components/FloatingNodeMenu.tsx, src/nodes/codeEditor.tsx, src/nodes/logViewer.tsx, src/nodes/table.tsx, src/nodes/textEditor/slate-editor-components.tsx, src/nodes/textEditor/textEditor.tsx, src/nodes/widgets/widgetNodes.tsx, src/utils/utils.ts
* Added option which creates a rich text node if you paste html or plain text right into the canvas
* Updated the way we are copying nodes -> now using the text/html mime type to better differentiate what is copy/pasted
* Added autoHeight option for the rich text node (on by default)
* Made the min-size of the rich text node smaller
* Moved the rest of the hybrid node functions into the hybridNode class
=> Text node updates and fixes

src/App.tsx, src/classes/GraphClass.ts, src/components/ContextMenus.tsx
Added an option to replace a node by
* right clicking it and choosing replace with in the context menu
* selecting a node and click ctrl/cmd + f
The action is undoable. Woohoo :-)
https://user-images.githubusercontent.com/4619772/195927611-a4051ee2-f113-4d1d-8e5f-933ee939c84b.mp4
=> Add option to replace a node

package.json, src/classes/HybridNode.ts, src/classes/NodeClass.ts, src/nodes/allNodes.ts, src/nodes/codeEditor.tsx, src/nodes/draw/html.tsx, src/nodes/table.tsx, src/nodes/textEditor/textEditor.tsx, yarn.lock
Added an html render node which allows to embed any iframe code (youtube, vimeo, website). Unfortunately we can not embed our github page, as it disallows embedding.
=> Html renderer node

webpack.config.ts
Prevent Invalid Host header error in codesandbox
=> Prevent Invalid Host header error in codesandbox

src/nodes/table.tsx
=> Added sorting to table node

src/classes/GraphClass.ts, src/classes/NodeClass.ts, src/classes/SocketClass.ts, src/components/ContextMenus.tsx, src/nodes/data/dataFunctions.tsx, src/nodes/data/json.tsx
Fixes
* trigger sockets not actually being removed
* the node not resizing, when removing sockets in general
* trigger connections not being copied
* replacing nodes with connected triggers
=> Fix trigger socket not being removed and resize issue

src/nodes/draw/abstract.tsx, src/nodes/draw/draw.tsx
This might break existing graphs. Loading should still work, but the rotation might be wrong and in case it had a link, the link would have to be moved to the angle input.
I have also changed some of the inputs (width, height, offsetx/y) to integer as I think it makes more sense.
=> change rotation to angle

src/classes/HybridNode.ts, src/classes/NodeClass.ts, src/nodes/codeEditor.tsx, src/nodes/data/dataFunctions.tsx, src/nodes/draw/html.tsx, src/nodes/table.tsx, src/nodes/text.tsx, src/nodes/textEditor/textEditor.tsx, src/nodes/widgets/widgetNodes.tsx
* Added a dropdown widget with single and multi select option
* Added label option to all widgets
=> Add dropdown widget

src/nodes/table.tsx
I noticed that I had made a mistake on the JSON output of the table node. It was wrongly outputting the raw sheet data. Sorry that I have only noticed it after you had written the extra nodes.
* I have changed the JSON output to actually output JSON. As this is the same as what your Table_GetRowObjects node had done, this node was not needed anymore.
* The raw sheet data is already included in the workbook output, in case this is ever needed
* I have changed your accompanying nodes to be based on the ArrayOfArrays output which made them a bit simpler
=> Fix json output for table node

src/App.tsx, src/classes/LinkClass.ts, src/nodes/allNodes.ts, src/nodes/utility/browser.ts
* Added an open url node
* Fixed an issue where folders in the examples repo would be listed in the graph search
=> add open url node and small fixes

src/nodes/table.tsx, src/utils/utils.ts
* Added right click option to add rows above/below and remove row
=> Add row menu

src/classes/SocketClass.ts, src/nodes/datatypes/abstractType.tsx, src/nodes/datatypes/triggerType.tsx, src/widgets.tsx
* Fixes issue that socketShouldAutomaticallyAdapt being applied to triggerSockets?
* Small styling change of trigger Socket widget
=> fix trigger socket issues

src/App.tsx, src/InterfaceController.ts, src/classes/GraphClass.ts, src/nodes/draw/abstract.tsx, src/nodes/macro/macro.ts
more polish to be added, but pretty happy with this conceptually
=> Allow mouse dragging around anything drawable (unless class blocks it specifically)

src/nodes/utility/utility.ts
The node has all parameters the lodash debounce function has.
If you change the parameters, you need to call the update trigger. This creates a new debounce function with the new values. Having to press the update trigger button is not very elegant, but I was not sure how else to do this.
=> Add debounce node

src/nodes/data/dataFunctions.tsx, src/nodes/utility/utility.ts
Added a convenience node for npm loading.
The console log inside the custom function is for listing the supported methods in the console. That was the easiest for now.
=> Load npm node

src/App.tsx, src/PPStorage.tsx, src/utils/constants.tsx
* Added a new url parameter to support opening a new playground -> `/?new=true`
* With this change, the welcome playground is loaded if
* there are no saved local graphs and there is no loadURL parameter
Note: most changes in PPStorage is from prettifier.
=> Add new option and load get started graph by default

src/nodes/table/table.tsx
Added
* when clicking on column context menu
* Get column data
* when clicking on cell context menu
* Get cell data
* Get row data (as array)
* Get row data (as object)
And I added an offset so the nodes are getting created to the right of the table
=> More table menu options

src/App.tsx, src/components/JsonPathPicker.tsx, src/utils/utils.ts
Pasting a URL now results in creating an embed website node.
https://user-images.githubusercontent.com/4619772/215586428-e6479dcf-bb2c-43c8-a772-321362cf9b46.mov
=> Added option to paste URLs

src/PropertyArrayContainer.tsx, src/components/Editor.tsx, src/components/FloatingJsonPathPicker.tsx, src/nodes/base.ts, src/nodes/draw/draw.tsx, src/utils/constants.tsx, src/utils/utils.ts, src/widgets.tsx
Some small fixes
* fixed array comparison in useInterval
* added useInterval to the codeEditor which now seem to updated properly
* added a character limit to string input
* added drawingOrder to the DRAW_COMBINE_ARRAY
* fixed an issue with the floating json picker
* Screen coordinates of the mouse cursor are now integer
=> Some fixes

src/nodes/widgets/widgetNodes.tsx
* now the last slider value is saved :-)
* fixes some of the widget nodes not getting an initial value
=> Last slider value is saved and fix missing initial widget values

src/nodes/table/table.tsx
* added option to input
* Either array of arrays
* Or array of objects
* added option to save/download the current sheet of the table in different formats
* xlsx (exports all sheets)
* csv
* txt
* html
* rtf
https://user-images.githubusercontent.com/4619772/220729494-a75439ca-fe2c-423a-9f2f-31f67353d08e.mov
=> Improve table

src/classes/HybridNode2.tsx, src/classes/NodeClass.ts, src/nodes/textEditor/textEditor.tsx, src/utils/style.module.css
* Adding an edit button for hybrid nodes
* It acts the same way as a double click
* Turned the hybridNode file into JSX
* Fixed a crash with the textEditor node
=> Add edit button to hybridnode

src/components/Editor.tsx
* fixes an issue where the editor height was not updated
* fixes an issue where you could end up loading the full length right away as it would not check the length when content changes
=> fix editor height

src/App.tsx, src/PPStorage.tsx, src/components/Search.tsx, src/nodes/text.tsx, src/utils/utils.ts
* Fixed the save new and rename issue
* Added option to download any local graph
* Added cut option
* Fixed possible color error for label
* Small search cleanup
=> Fix save and rename issue

src/classes/SelectionClass.ts, src/nodes/text.tsx
It is not perfect but I think its a lot better, there are also some visual bugs fixed
=> Label refactor

src/classes/GraphClass.ts, src/components/ContextMenus.tsx, src/components/Search.tsx, src/nodes/data/dataFunctions.tsx, src/nodes/data/json.tsx, src/nodes/datatypes/abstractType.tsx, src/nodes/datatypes/anyType.tsx, src/nodes/datatypes/arrayType.tsx, src/nodes/datatypes/booleanType.tsx, src/nodes/datatypes/codeType.tsx, src/nodes/datatypes/colorType.tsx, src/nodes/datatypes/deferredPixiType.tsx, src/nodes/datatypes/dynamicEnumType.tsx, src/nodes/datatypes/enumType.tsx, src/nodes/datatypes/functionType.tsx, src/nodes/datatypes/imageType.tsx, src/nodes/datatypes/jsonType.tsx, src/nodes/datatypes/numberType.tsx, src/nodes/datatypes/stringType.tsx, src/nodes/datatypes/triggerType.tsx, src/nodes/draw/draw.tsx, src/nodes/graphSegments/simpleBarGraph.json, src/nodes/state/stateNodes.ts
* added datatype suggestions
* removed defaultInputNodeWidget and defaultOutputNodeWidget and exchanged it with the first element in the new suggestions
* removed Map node and renamed MapSequential
=> Added datatype suggestions

src/classes/NodeClass.ts, src/classes/SelectionClass.ts, src/nodes/datatypes/abstractType.tsx, src/nodes/datatypes/arrayType.tsx, src/nodes/widgets/widgetNodes.tsx
Feel free to change any of the styling if you want to
=> Simple radio widget

src/nodes/draw/abstract.tsx, src/nodes/draw/draw.tsx
Added latest pressed outputs to the following nodes
* combine draw
* multiply onto points
Note, that Last pressed injected is broken - https://trello.com/c/spdOlpXi
=> Add latest pressed outputs

src/nodes/utility/utility.ts
* Added a write to clipboard node
=> Add write to clipboard node

src/classes/GraphClass.ts, src/nodes/graphSegments/segmentNode.tsx
* added the ability of keeping the data when copy pasting nodes which have connections which are not copied
* added the execution of all seed nodes when pasting
https://github.com/fakob/plug-and-play/assets/4619772/66abf414-edda-4329-ac20-cafa1e088e17
=> Include data of connected sockets

src/nodes/draw/html.tsx, webpack.config.ts
* fixed the issue that the HtmlRenderer node completely re-rendered by memoizing it and only listen to
* added a reload button
=> Fix html node reload

src/nodes/widgets/widgetNodes.tsx
* Auto font size for button, slider, color picker and switch
compared to
=> Auto font size for button, slider, color picker and switch

src/App.tsx, src/PropertyArrayContainer.tsx, src/classes/GraphClass.ts, src/classes/NodeClass.ts, src/classes/SelectionClass.ts, src/nodes/graphSegments/segmentNode.tsx, src/utils/interfaces.tsx, src/utils/utils.ts
* Added option to alt+drag to duplicate
* Made pasteNodes undoable
https://github.com/fakob/plug-and-play/assets/4619772/6821de3d-b29f-461e-b53a-f32a968cdc23
=> Alt drag to duplicate

src/classes/NodeClass.ts, src/classes/SocketClass.ts, src/nodes/macro/macro.ts, src/widgets.tsx
=> nicer (?) display names for macro parameters

src/InterfaceController.ts, src/classes/NodeClass.tsx, src/nodes/text.tsx
* Added hiding tooltip on escape
* Added exiting hybrid/double clicked nodes on escape
=> Escape for tooltip and node

src/classes/HybridNode2.tsx
After clicking of the edit button in the top right corner of a hybrid node you would not be able to click outside or escape out of it.
=> Fix hybrid node edit button not losing focus anymore

src/classes/GraphClass.ts, src/classes/LinkClass.ts, src/classes/NodeClass.tsx, src/classes/SocketClass.tsx, src/dragAndDrop.ts, src/nodes/codeEditor.tsx, src/nodes/data/dataFunctions.tsx, src/nodes/draw/abstract.tsx, src/nodes/draw/video.tsx, src/nodes/macro/macro.ts, src/nodes/text.tsx, src/nodes/widgets/widgetNodes.tsx, src/utils/utils.ts
gonna add make json and combine graphics to this concept as well (unless you protest)
=> Dynamic inputs

assets/examples/Get frames from a video.ppgraph, src/App.tsx, src/InterfaceController.ts, src/PPStorage.tsx, src/PnPHeader.tsx, src/components/ResponsiveDrawer.tsx, src/components/Search.tsx, src/utils/actionHandler.tsx, src/utils/style.module.css
* moved header bar with search into its separate component/file
* added option to easily rename graphs
* added a save image button to the video example
=> Pnp header improvements

src/dragAndDrop.ts, src/nodes/allNodes.ts, src/nodes/data/xml.tsx
* Added an XML reader node which
* dynamically loads the xml2js package
* allows conversion from XML to JSON
=> Xml reader

README.md, src/classes/GraphClass.ts, src/dragAndDrop.ts, src/nodes/image/image.ts, src/utils/dynamicImport.tsx
* Added a dynamic import of ExifReader which uses the Mozilla Public License 2.0 (MPL-2.0)
* Added check if the dynamic import already exists
* Added before and after toast messages for installing packages
* Removed ensureVisible when dragging in as it felt more natural to not move them into the center, but just leave them where you had dropped them
=> Add exif reader to image node

src/nodes/api/http.tsx
I suggest to only adapt the output?
=> Fix for header switching to string on http node

src/classes/GraphClass.ts, src/classes/HybridNode2.tsx, src/classes/NodeClass.tsx, src/classes/SocketClass.tsx, src/nodes/allNodes.ts, src/nodes/base.ts, src/nodes/codeEditor.tsx, src/nodes/data/dataFunctions.tsx, src/nodes/draw/html.tsx, src/nodes/draw/video.tsx, src/nodes/graphSegments/segmentNode.tsx, src/nodes/image/image.ts, src/nodes/image/shader.ts, src/nodes/table/table.tsx, src/nodes/text.tsx, src/nodes/utility/database.ts
This is a lower energy version of the constructor demotion, but it is safer and should give the same (?) performance increase, there is definitely room for further improvements though
=> Constructor demotion 2

src/InterfaceController.ts, src/nodes/text.tsx
* Added a Text node based on the Label node which
* is transparent
* has all sockets hidden
* can be added pressing T
https://github.com/fakob/plug-and-play/assets/4619772/4d2eedda-1bbd-4c28-8aad-25e52a7c106f
=> Added transparent text label

src/nodes/draw/html.tsx
* added a header socket which allows to add code in the header of the html node
* as default example we are loading tailwind and style the text with it
=> allow header injection for html node

src/classes/GraphClass.ts
Is it this what we want for executeAllSeedNodes?
* execute all nodes which
* do not have any dependencies
* AND have on load enabled
=> Update executeAllSeedNodes logic

src/GraphInspectorContainer.tsx, src/NodeArrayContainer.tsx, src/NodeInspectorContainer.tsx, src/PPStorage.tsx, src/PropertyArrayContainer.tsx, src/SourceContent.tsx, src/classes/GraphClass.ts, src/classes/NodeClass.tsx, src/classes/SocketClass.tsx, src/nodes/data/dataFunctions.tsx, src/nodes/datatypes/jsonType.tsx, src/nodes/table/table.tsx, src/utils/utils.ts, src/widgets.tsx
…ts called in interface, sped it up
there are more things I found I will fix
=> Significant performance improvements when dealing with larger data

src/LeftsideContent.tsx, src/PPStorage.tsx
In Dexie.js there is no easy way of returning just some values. https://github.com/dexie/Dexie.js/issues/468
If this becomes an issue, we can look into some of the suggested solutions.
* I have removed the double sort
=> Tiny getGraph improvement

src/components/GraphOverlayDrawer.tsx
Fix issue with playground border
=> Fix issue with playground border

cypress/e2e/pnp/checkNodesForErrors.cy.ts, src/classes/ErrorClass.ts, src/components/GraphOverlayDrawer.tsx, src/components/JsonPathPicker.tsx, src/nodes/data/json.tsx, src/nodes/datatypes/jsonType.tsx, src/nodes/image/image.ts, src/nodes/table/tableHelpers.tsx, src/nodes/utility/database.ts, src/utils/utils.ts, src/widgets.tsx
* Fixed error on creation of SqliteReader, Image, JSONSet, Table_GetColumnByName
* Added warning class
* Updated tests
=> Fix creation errors of some nodes

cypress/e2e/pnp/testWidgetNodes.cy.ts, src/TestController.ts, src/nodes/widgets/widgetNodes.tsx
Fixes this issue - https://trello.com/c/DpnYhJBz
=> Fixed bug with dropdown node when toggling multi selection

cypress/e2e/pnp/mouseInteractions1.cy.ts, cypress/e2e/pnp/mouseInteractions2.cy.ts, src/App.tsx, src/classes/GraphClass.ts, src/classes/NodeClass.tsx, src/components/Search.tsx
* Fixed the issue where removing a link from a socket which has multiple links, would remove all of them
* Updated one of the tests to cover this case
* Renamed some variables
=> Fix issue where remove link would remove all links

src/InterfaceController.ts, src/pixi/utils-pixi.tsx
* use ctrl/cmd + and - to zoom in and out
=> add keyboard zoom

.github/workflows/main.yml, assets/examples/Draw charts using Observable Plot-d3.ppgraph, assets/examples/Draw charts using chartjs.ppgraph, assets/examples/Draw three.js.ppgraph, cypress/e2e/pnp/parallelizable/testHybridNodes.cy.ts, cypress/e2e/pnp/parallelizable/testMultiplyObject.cy.ts, cypress/fixtures/listExamples.json, src/TestController.ts, src/nodes/draw/html.tsx, webpack.config.ts
* Added an html element output socket, which outputs a reference to the html element which is displayed
* Updated the graphs which had hardcoded this
* Added 2 more simple HTML nodes which just output a div/canvas
* Added 2 more examples using the observable plot library and the three.js library
=> Add html element output socket

cypress/e2e/pnp/helpers.ts, cypress/e2e/pnp/parallelizable/mouseInteractions1.cy.ts, src/classes/NodeClass.tsx
* Fix shift click to add to selection
* Updated test for it
=> Fix shift click to add to selection and updated test

src/nodes/utility/utility.ts
* Added a node using the hash-wasm library
* It supports a wide range of hash functions some of which need an object as input. As this needs some more knowledge, I have added a link to the documentation in the info.
* for the HMAC function you can also define the hash method, and a key
https://github.com/fakob/plug-and-play/assets/4619772/83df2b98-fca3-49f1-920f-aba1031748ad
=> Add hash node

src/GraphInspectorContainer.tsx, src/NodeInspectorContainer.tsx, src/PropertyArrayContainer.tsx, src/SocketContainer.tsx, src/SourceContent.tsx, src/nodes/datatypes/enumType.tsx, src/nodes/datatypes/numberType.tsx, src/widgets.tsx
Made the inspector UI more compact
=> More compact UI

src/nodes/text.tsx, src/utils/constants.tsx, src/widgets.tsx
* Fixed bgcolor not changing
* For the label node, we are using the actual node background. Therefore we also need to redraw drawNodeShape()
* Also fixed an issue with the newly introduced color type
=> Fix label node bgcolor not changing

cypress/e2e/pnp/parallelizable/duplicate.cy.ts, src/TestController.ts, src/pixi/utils-pixi.tsx
dont know if this will bring back the leak we had....
=> disabled destroying of texture and basetexture to avoid image crash
