src/nodes/data/json.tsx
When reloading the Get example the JSONKeys and JSONValues nodes kept throwing an error and the wiring would not show up. I think it was due to the array lookup getting an undefined or null value in some cases.
=> Make JSONKeys and JSONValues node more lenient

src/classes/GraphClass.ts, src/classes/NodeClass.ts, src/classes/SelectionClass.ts, src/components/GraphOverlay.tsx, src/components/GraphOverlayNodeMenu.tsx
I suggest to hide the node menu overlay during these actions. 
* the node was dragged
* the selection was dragged (multiple nodes)
* the viewport was dragged or zoomed
I found out that the node menu re-rendered on all these actions. This was particularly heavy as the menu had included a serialize node method in there. Maybe that could also be improved, but hiding it helps already a lot. Please have a look
=> Node dragging performance improvement

src/App.tsx, src/classes/GraphClass.ts, src/utils/constants.tsx, src/utils/interfaces.tsx
Added saving and loading of viewport position and scale. So after loading you see the exact same section of the graph you had when saving.
For this I have also added a bit more debugging info. Mouse and viewport coordinates on the top left and a grid shader texture spanning from 0,0 - 1000,1000.
=> Store viewport position

src/components/ContextMenus.tsx
This should fix the overlapping context menu on windows.
Somehow the browser context menu is triggered on the actual context menu on windows. Not sure why Mac and Windows behave differently.
=> Fix for overlapping context menu on windows

src/classes/GraphClass.ts
I saw that the duplicateSelection did not work anymore as it was not duplicating the links. I have now removed the async await from the loop which creates the nodes as the nodes are needed before we can start creating the new links.
=> Fix duplicateSelection losing links

src/App.tsx, src/classes/GraphClass.ts, src/classes/SelectionClass.ts
Something different I worked on the weekend. I tried to make the pan and zoom handling more similar to Miro/Blueprints and it seems to work well for me. I tested it on a Mac and a Pc with trackpad and mouse. It might need some more testing on different devices. This is the new behaviour:
* Drag with trackpad or middle or right mouse click
* Zoom with trackpad using pinch or ctrl scroll
* Zoom with mouse using scrollwheel
* Select with left click (shift key is only need for adding or subtracting the selection)
=> Improve pan zoom handling

src/App.tsx, src/utils/utils.ts
I have changed 
* the copy event
* if text selection is empty when the copy event occurs we prevent the default action and copy selected nodes into the clipboard
* the paste event
* we get the text from the clipboard and try to parse it, if it is parseable we prevent the default and create nodes, if not we let it pass and let the default paste action go through
=> Fixing copy paste

src/utils/xlsxspread.ts
The included script transforming the data between x-spreadsheet and sheetjs had a very lax threshold for detecting/formatting string data to numbers. I have now added a stricter number conversion of cell data.
=> Fixing issue messing with table data when editing

src/classes/GraphClass.ts
I found a bug when trying out the latest graph you sent. Loading did not work because the configure function was expecting a customNodeType object. Your graph did not have that.
=> Fix issue uploading a graph  not working, when no custom nodes stored

src/App.tsx, src/classes/GraphClass.ts
This fixes
* a bug where the node was not inserted at the correct place. I had doubled up the toWorld calculation.
* a bug where a selection rectangle was drawn when trying to unplug/replug a socket
* a bug where the viewport context menu would be cut off when right clicked too low on the screen
https://user-images.githubusercontent.com/4619772/176955279-a9c56f87-a345-4c4f-aed1-ef1067f40484.mp4
=> Fixing insert and socket clicking bug

src/components/FloatingSocketInspector.tsx, src/components/GraphOverlaySocketInspector.tsx
This fixes a crash of react when the floating inspector is open and its node gets deleted.
=> Fix react crash due to inspector

src/classes/NodeClass.ts
The original socket value is lost after
* linking a value
* saving the graph
* reloading the graph
* then unlinking it
=> Fix losing defaultData

src/App.tsx
Added an option to load a graph from a link included in the URL.
How to:
1. Upload your graph to e.g. github
2. Get the "raw" URL to the file
3. Add the URL as the value of the URL parameter `loadURL`
Example:
`http://localhost:8080/?loadURL=https://raw.githubusercontent.com/fakob/plug-and-play-examples/dev/Get%20API%20example.ppgraph`
NOTE:
We have a dedicated [repo for graphs](https://github.com/fakob/plug-and-play-examples) where you could upload yours. The dev branch is grabbed and shown in the graph dropdown. If you do not want it to show up there, just create a new branch.
=> Load graph via url

src/components/Editor.tsx, src/utils/style.module.css
This should fix the issue with the code editor height in the side bar. The editor is now resized based on content height with a minimum and a maximum value.
=> Fix code editor height

src/PropertyArrayContainer.tsx
using direct imports for mui icons brought down the size significantly. from 5.56MB ->  16KB
```
import MoreVertIcon from '@mui/icons-material/MoreVert';
import LockIcon from '@mui/icons-material/Lock';
import VisibilityIcon from '@mui/icons-material/Visibility';
import VisibilityOffIcon from '@mui/icons-material/VisibilityOff';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
```
instead of 
```
import {
MoreVert as MoreVertIcon,
Lock as LockIcon,
Visibility as VisibilityIcon,
VisibilityOff as VisibilityOffIcon,
ExpandMore as ExpandMoreIcon,
ContentCopy as ContentCopyIcon,
} from '@mui/icons-material';
```
mui states that it should not matter as tree-shaking of webpack should take care of it, but somehow it does …
=> direct imports for mui icons

package.json, yarn.lock
Ahhhhhhh
Honestly, I am not sure what has changed, but I have now upgraded pixi.js to the latest version and it seem to have worked. We will see it only when merging and pushing to heroku I guess. 
Another thing I have done is set the data table to the previous to last version. They have made a change which breaks our install with yarn. It looks for the npm lock file which we do not have as we are running yarn. Anyway I hope we get the new data table to work.
=> upgrade pixi and fix table version

src/PropertyArrayContainer.tsx, src/classes/GraphClass.ts, src/classes/NodeClass.ts, src/classes/SocketClass.ts, src/nodes/data/dataFunctions.tsx, src/nodes/widgets/widgetNodes.tsx, src/utils/interfaces.tsx
* I have introduced a nodeTriggerSocketArray, which is being used if you right click add a node trigger socket
* Though it is still possible to use triggerType on normal inputs
* The node trigger sockets are displayed on the top before the outputs
* I have updated the look of trigger types to be square
* I have updated the addTriggerInput function to also turn off "Update on change" as this is probably always what you want when adding a nodeTriggerSocket
=> Move trigger sockets out of socket array

src/classes/GraphClass.ts, src/classes/NodeClass.ts, src/nodes/base.ts, src/nodes/logViewer.tsx, src/nodes/table.tsx, src/nodes/text.tsx, src/utils/utils.ts
This feature allows you to drag connections from inputs or outputs directly onto another node.  In addition I have also added both preferred input and output socket index. The logic is:
* if node has a preferred socket index without connection > use it
* if node has a socket with the same type without connection > use it
* if node has a AnyType socket without connection > use it
* if node has a socket without connection > use it
* if all sockets have connections, connect to preferred socket, else connect to first socket
I have gone through some of the nodes and added preferred sockets were I thought it fits.
=> Drag link on node

src/App.tsx, src/InspectorContainer.tsx, src/classes/GraphClass.ts, src/classes/SocketClass.ts, src/components/ContextMenus.tsx, src/nodes/base.ts, src/nodes/data/dataFunctions.tsx, src/nodes/datatypes/codeType.tsx, src/nodes/datatypes/jsonType.tsx, src/nodes/datatypes/stringType.tsx, src/nodes/text.tsx, src/nodes/textEditor/slate-editor-components.tsx, src/nodes/textEditor/textEditor.tsx
* When right clicking a socket or its name, you can connect a node. Now, if it is an input socket, the data is transferred over to the new node. This way you can break out data into separate nodes. This also works when there was a previous connection.
* Before the right clicking was only possible on the text. As hybrid nodes do not have a text, I have removed the "right click a socket removes the link" and moved it into the context menu. This might be controversial, but I was not sure how else to do this
* Added more defaultInput/OutputWidget definitions for some types
* Added option for Label, Constant node to receive initial data
* Added optional date string input for DateAndTime node
* Added plain text output for TextEditor
* Fixed txt import
* Fixed socket right click no longer …
=> node-updates-2

src/classes/GraphClass.ts, src/classes/HybridNode.ts, src/classes/NodeClass.ts, src/nodes/base.ts, src/nodes/text.tsx, src/nodes/textEditor/textEditor.tsx, src/nodes/widgets/widgetNodes.tsx, src/utils/utils.ts
* Rewritten how the vertical resizing of the textEditor node is handled. I am now using a resizeObserver to listen to size changes. That works a lot better and does not require timeouts anymore
* Fixed an issue of hybrid node sizes not being correct
* added a getter for the viewport scale
=> Improve texteditor

src/components/Search.tsx
I had accidentally removed the ability add custom nodes via typing a new node name.
=> add back create custom node

src/App.tsx, src/classes/GraphClass.ts
This has been annoying me for some time, when you disconnect a link by dragging output first, it pops up browser, made it only happen if there is no input from before
=> made node browser not appear if old link had input

src/nodes/base.ts, src/utils/utils.ts
This fixes an issue when removing the mouse node. I was overwriting `onNodeDragOrViewportMove` which existed on the nodeclass and that created an issue when the mouse node unsubscribed the one from the nodeclass.
=> Fix issue when removing mouse node

src/nodes/draw/html.tsx
Added a node to embed websites. It essentially is an html node, but has just a simple iframe code in there. This should make it a tidbit easier for users who do not know much about iframes and how to use them.  It can still be made easier so you only need to write a URL and don't see any iframe code, but for now I believe it is ok.
It loads a random wikipedia article by default.
=> Iframe node

src/components/Search.tsx
Added option for remote graphs to
* open in new tab
* copy URL
=> Add option to open in new tab and copy URL

src/App.tsx, src/InspectorContainer.tsx, src/components/ContextMenus.tsx, src/components/GraphOverlay.tsx, src/components/GraphOverlayDrawer.tsx, src/components/ResponsiveDrawer.tsx
This is the first step of some improvements regarding the inspector
* the right side drawer can now be toggled
* using an icon in the top right (visible if a node is selected)
* using a keyboard shortcut ctrl+\
* using toggle entries in the graph and node menus
=> Improve inspector

src/App.tsx, src/utils/utils.ts
I kept running into the following issue
* I loaded a graph via the loadURL parameter
* I made a change and saved it as a new graph
* for whatever reason I had to reload the page
* now, due to the loadURL parameter, the old graph gets loaded and not what I was expecting the one I was working on in the meantime
This PR suggests to remove the parameter right after it has been loaded. The browser history is kept so one can go back to it.
=> Remove loadURL parameter after loading

src/classes/NodeClass.ts, src/nodes/base.ts, src/nodes/data/array.tsx, src/nodes/datatypes/triggerType.tsx, src/nodes/draw/abstract.tsx, src/nodes/draw/draw.tsx, src/nodes/image/image.ts, src/nodes/macro/macro.ts, src/nodes/math.ts, src/nodes/state/stateNodes.ts, src/nodes/utility/playground.tsx, src/nodes/utility/utility.ts, src/utils/constants.tsx, src/widgets.tsx
Fixed an issue with the dropdown/enumType where mainly the pivot property in the drawing nodes was not correctly selected after reload. Back in the day I was not consistent in how to handle the dropdown component and what values to use. This I have fixed and have made more consistent.
* Enum/Dropdown options should be an array of objects which have at least a `text` property. No other property is required
* Optionally you can add a `value` property in case you need a separate value. Getting the value would have to be done individually in the node itself
* However when saving, only the `text` property is stored in the socket. An optional `value` would have to be looked up
Also updated the RandomArray node as it had an old school implementation of a node trigger.
=> Fix dropdown/enum options and some cleanup

src/App.tsx, src/InspectorContainer.tsx, src/InterfaceController.ts, src/PropertyArrayContainer.tsx, src/SocketContainer.tsx, src/classes/GraphClass.ts, src/classes/NodeClass.ts, src/classes/SocketClass.ts, src/components/ContextMenus.tsx, src/components/FloatingSocketInspector.tsx, src/components/GraphOverlay.tsx, src/components/GraphOverlayDrawer.tsx, src/components/ResponsiveDrawer.tsx, src/index.tsx, src/nodes/graphSegments/simpleBarGraph.json, src/utils/constants.tsx, src/utils/interfaces.tsx, src/utils/style.module.css, src/widgets.tsx
* When clicking on a socket
* the inspector opens
* switches to the respective filter
* scrolls to and marks the socket
* moved the toast messages to appear in the center, to not cover the drawer button
* moved the share button to the top left
https://user-images.githubusercontent.com/4619772/215353983-baccb990-f80a-4988-9960-c49baa60cf0e.mov
=> Socket click to focus

src/App.tsx, src/PPStorage.tsx, src/classes/GraphClass.ts, src/utils/actionHandler.tsx
* Added an unsaved changes warning when
* closing or reloading a tab/window -> shows standard close/reload tab browser dialog (no control over design or text)
* loading another graph -> shows the browsers default confirmation dialog (no control over design)
* for this case we can add a react modal dialog in the future to make it prettier
=> Unsaved changes warning

src/SocketContainer.tsx, src/components/Editor.tsx, src/utils/actionHandler.tsx, src/widgets.tsx
This PR fixes 2 different bugs
* react crash due to `String(asdf)` not being able to handle object data which does not have a toString() method
* issue where, when switching between nodes, the socket types would not update on first click
https://user-images.githubusercontent.com/4619772/217668110-95a382e9-d5f8-4b33-9294-b1b17a0f789a.mov
https://user-images.githubusercontent.com/4619772/217668111-02cb9aa9-10a8-4ffe-a45f-0c57a1639630.mov
=> Fix react crash and socket not updating right away

src/App.tsx, src/components/Search.tsx
This PR
* fixes 3 different MUI autocomplete errors. Passing null instead of undefined is necessary for the MUI component to be considered a controlled component 
* changes the node search function to be more flexible - let's see if we like this better
=> Fixed mui autocomplete errors

src/classes/LinkClass.ts
Regarding the issue where when selecting all nodes, and deleting them, they would not be deleted in one go and raise an error in this row:
```this.getTarget().getNode().executeOptimizedChain();```
I am still not sure why this only happens sometimes, but I am pretty sure that the issue is based on the fact that the links are being deleted asynchronously after the node is being destroyed:
When deleting a node:
* the node is destroyed
* an event is emitted
* onRemoved is triggered which then removes all the links
And therefore having above in the delete function can sometimes throw an error as the node does not exist anymore and can not be updated.
```
_onRemoved(): void {
// remove added listener from graph.viewport
PPGraph.currentGraph.viewport.removeListener(
'moved', …
```
=> Fix for not removing all nodes

src/App.tsx, src/classes/GraphClass.ts, src/classes/NodeClass.ts, src/nodes/text.tsx, src/utils/constants.tsx, src/utils/interfaces.tsx
This is a suggestion for what I called "node source", where serialized is the common one for loaded and pasted. I don't think we have to differentiate between them.
This PR also fixes the issue with the label node. It works even better now as it does not focus anymore when adding a new connected label.
```
export const NODE_SOURCE = {
NEW: 'New',
NEWCONNECTED: 'NewConnected',
SERIALIZED: 'Serialized',
} as const;
```
=> Adding node source and fix for label node

src/nodes/datatypes/triggerType.tsx
This fixes an issue where a trigger button, when using positive or negative flank, would not execute the first time after loading. In our welcome graph for example, you have to always click twice the first to open a URL.
This is due to the previousData being initially undefined and undefined > x or x < undefined is always false.
=> Fixes issue where trigger would not execute after loading

src/App.tsx, src/classes/GraphClass.ts, src/components/ErrorFallback.tsx
* Fixes a crash when replacing a node and clicking on one of the sockets right away. It looks for the old selection which was not updated
* I also added a "save as/save backup" button on the react error screen. Even though the graph could end up being broken, this might still be better than reloading and losing all the unsaved work
=> Fix replace node issue

src/components/ContextMenus.tsx
* the main menu is now scrollable and does not get cut off on smaller screens
* the gesture sub menu is now inlined on phones
https://github.com/fakob/plug-and-play/assets/4619772/739a0863-77d0-42e5-aca6-0af65b3a4d7a
=> Main menu mobile

src/classes/GraphClass.ts, src/classes/NodeClass.ts, src/classes/SocketClass.ts, src/nodes/datatypes/triggerType.tsx
There was always an issue with the trigger type where
* it would either trigger only after the second click (because the first one did a comparison with undefined)
* or it would execute right away on load
My previous fixes where not really helping. So what I did now is:
* on connection to a any socket the default value of the output is chosen, if the output data is undefined
* make using the defaultValue for socket inputs a loose comparison
* triggerType has gotten a default value (0)
* removed the old "fix"
=> fix trigger type issue

src/components/Editor.tsx
Added a check if the editor has focus. If so, do not shorten the text.
Fixes this issue - https://trello.com/c/NZyLl2SQ
=> Fix code editor issue when editing a long text

src/classes/SocketClass.ts
* Before, you could click on the socket rect as well as the text to re/disconnect. This interfered with the text clicking which opens the inspector on the right.
* Now, I have limited this to clicking on the socket rect, which also solves this - https://trello.com/c/57zuqE4F
In very rare cases, I have still observed that just clicking on a socket rect, could reconnect it. But I was not able to reproduce it
=> Fix trigger socket disconnect issue

src/classes/NodeClass.ts, src/classes/SelectionClass.ts, src/nodes/text.tsx, src/utils/utils.ts
* Added width to the label
* 0 or undefined is no width (as wide as text)
* you can change the width input or resize the node
* double clicking the resize icon, resets the width to 0
* Added `activeRescaling` parameter in `onNodeResize` to differentiate between actively rescaling with mouse or just calling it from somewhere else
* `onNodeResize` is now only called if the size has changed
* fixed a bug where a new HTMLTextComponent was appended every time one edited the text
* now all Labels share one single Label-Input div for editing text
https://github.com/fakob/plug-and-play/assets/4619772/4b022a74-447d-4e4f-8064-326a263f0e40
=> add width to label

src/PPStorage.tsx
Fixes the issue where when downloading a saved/renamed graph (and not downloading through the search graph dropdown)  the file name is using the id instead of the name.
=> fix download loosing name

src/classes/SelectionClass.ts
Fixes the following issue:
When a single node is selected, the selection should be ignored and not interfere with mouse interactions.
When hovering over a socket across the selection border the selection should not interfere which works fine until you zoom/pan. Then all of a sudden the selection is actually overlaying the node and interferes with it. See video
https://github.com/fakob/plug-and-play/assets/4619772/1dd79c99-4932-4e1c-8834-897d617ed215
=> Fix selection of single node overlapping after zooming or panning

src/classes/GraphClass.ts, src/classes/NodeClass.ts
When replacing a node (select and node search with ctrl+F), we currently
* replace the node
* overwrite all the data of the new node with the data of the original one
This creates a problem for example when replacing an Add node with a Subtract node as the code of the Add node gets kept from the Add node. See
https://github.com/fakob/plug-and-play/assets/4619772/6af4bfbd-cb89-4c98-893b-890ff4dd9c23
In this fix I am suggesting to only overwrite position and update behaviour, but not the socket data.
https://github.com/fakob/plug-and-play/assets/4619772/d8785d93-3c81-47ac-b851-ed2abdc165e5
=> Fix replace issue keeping old data

src/App.tsx, src/classes/GraphClass.ts, src/classes/SocketClass.ts, src/components/ContextMenus.tsx, src/nodes/datatypes/numberType.tsx
* Right clicking a socket now presents all preferred nodes (not just the first one)
* custom per node
* custom per socket type
* This step is now also undoable
* Added Label as a preferred node to the number type
=> Add more connect options to socket right click

.github/workflows/main.yml
For my PR I got a cypress test error. It seems I have to run node 16.
=> Update cypress tests to use node 16

src/classes/GraphClass.ts
This error happened when copy pasting a node which had a DeferredPixiType as input.
=> Fix error stringifying DeferredPixiType

src/App.tsx, src/classes/GraphClass.ts, src/classes/HybridNode2.tsx, src/classes/LinkClass.ts, src/classes/NodeClass.tsx, src/classes/NodeHeaderClass.ts, src/classes/SelectionClass.tsx, src/classes/SocketClass.tsx, src/classes/UpdateBehaviourClass.ts, src/components/FloatingSocketInspector.tsx, src/components/GraphOverlaySocketInspector.tsx, src/nodes/api/http.tsx, src/nodes/api/pixotopeGateway.tsx, src/nodes/base.ts, src/nodes/data/dataFunctions.tsx, src/nodes/draw/abstract.tsx, src/nodes/image/image.ts, src/nodes/image/shader.ts, src/nodes/interactivity/record.tsx, src/nodes/macro/macro.ts, src/nodes/math.ts, src/nodes/text.tsx, src/nodes/utility/browser.ts, src/nodes/utility/utility.ts, src/nodes/widgets/widgetNodes.tsx, src/widgets.tsx
I have structured the internals of the node layers a bit and separated them into
* background
* pretty much the whole node including background, header, sockets
* foreground
* what ever is rendered, either on top of it (in case of widgets), or outside of it (in case of render nodes)
=> Structured node drawing into background and foreground groups

src/App.tsx, src/PPStorage.tsx, src/components/ContextMenus.tsx, src/components/Search.tsx, src/utils/style.module.css
* updated the graph search header
* now it shows the name of the selected graph
* added save option
* moved the share button inside the bar
* added a create new/empty graph button
* made it work for small screens
* added share option to context menu
=> Update graph search header

src/InterfaceController.ts, src/utils/inputParser.ts, src/utils/utils.ts
When using Shift+2 or Shift 1 inside the label, it would detect the zoom commands instead of writing @ or !
I noticed that we had two functions for it
* isEventComingFromWithinTextInput
* isEventComongFromWithinWidget
I have now consolidated them into 1. Not sure what the reason was why we/I had thought that there has to be a difference. Do you know?
=> Fix event from within text input issue and small cleanup

assets/examples/z debug missing nodes, sockets and links.ppgraph, src/GraphInspectorContainer.tsx, src/InspectorContainer.tsx, src/NodeArrayContainer.tsx, src/PPStorage.tsx, src/PropertyArrayContainer.tsx, src/classes/GraphClass.ts, src/classes/NodeClass.tsx, src/classes/SelectionClass.tsx, src/components/ResponsiveDrawer.tsx, src/dragAndDrop.ts, src/nodes/api/http.tsx, src/nodes/macro/macro.ts, src/pixi/utils-pixi.tsx, src/utils/constants.tsx, src/utils/utils.ts
* Added a node browser which
* shows all nodes in a graph
* nodes with errors and macros are on top
* hovering over a node in the list shows a focus border around the node in the graph
* clicking on a node in the list centers the node
* double clicking on a node in the list centers and zooms in onto the node
* clicking the select node button on a node in the list, selects the node
* using the arrow in the top of the drawer, let's you go back to the node browser
* the INFO tab shows
* a description we can add in the future
* the JSON of the graph which can be edited and with the replace button be loaded again
* Changed the default name of a node on creation to NOT be the node type, but the given name (getName())
* Updated the "missing nodes test" example …
=> Add node browser

src/utils/utils.ts
Fixed an issue we had in our copy paste logic which was triggered when copy pasting the Html node. 
This escaping and unescaping should be a lot cleaner now.
=> Fix copy paste issue

src/App.tsx, src/PPStorage.tsx, src/utils/constants.tsx, src/utils/utils.ts
Added a URL parameter (`loadLocal`) when a local graph is loaded. This allows you to
* load different graphs in different tabs
* go back and forth between different graphs
If there is no `loadLocal` parameter, we fall back to loading the last saved graph.
https://github.com/fakob/plug-and-play/assets/4619772/8be456b8-588f-474c-b756-0fef065c3b45
=> Add individual urls

assets/examples/Drawing a chart with chartjs.ppgraph, src/components/Editor.tsx, src/nodes/datatypes/functionType.tsx, src/nodes/utility/utility.ts
* fixes
* the chartjs example crash
* the issue that the loaded npm package node output could be detected as JSON and then lose all its class members when passed into the custom function input. For this I have made the functionType to not automatically adapt
=> Fixing chartjs example crash and loading issue

src/nodes/datatypes/arrayType.tsx, src/nodes/datatypes/codeType.tsx, src/widgets.tsx
* Fixes the issue when typing in the code editor for arrayType, it would immediately parse - https://trello.com/c/ip3OsxHO
* Fixed using the same principal as for the JSONWidget (Not a JSON alert)
https://github.com/fakob/plug-and-play/assets/4619772/0b4de6fb-07ca-4ab8-a6e0-a3f7fed6d7fe
=> Fixed typing in the code editor for arrayType

src/PropertyArrayContainer.tsx, src/classes/GraphClass.ts, src/classes/HybridNode2.tsx, src/classes/NodeClass.tsx, src/classes/UpdateBehaviourClass.ts, src/nodes/allNodes.ts, src/nodes/api/chatgpt.tsx, src/nodes/api/jira.tsx, src/nodes/api/pixotopeGateway.tsx, src/nodes/base.ts, src/nodes/data/test.tsx, src/nodes/data/xml.tsx, src/nodes/draw/abstract.tsx, src/nodes/draw/html.tsx, src/nodes/graphSegments/simpleBarGraph.json, src/nodes/image/shader.ts, src/nodes/macro/macro.ts, src/nodes/table/table.tsx, src/nodes/utility/browser.ts, src/nodes/utility/utility.ts, src/nodes/widgets/widgetNodes.tsx
* Added an "Update on load" option which executes the node after everything has been loaded
* This is helpful for nodes like the HTTP node or Custom functions which should be executed once the graph is loaded, but which you might not want to update always on change
This is different from "Execute on place" which is executed when nothing is connected. It makes sense to keep this hidden away from the user as some nodes rely on it.
=> Add update on load

src/classes/NodeClass.tsx, src/nodes/abstract/DynamicInputNode.ts, src/nodes/data/dataFunctions.tsx, src/nodes/data/json.tsx, src/nodes/math.ts
The custom function node was using `getAllInputSockets` to `adaptInputs` which would remove also the manually added sockets.
=> Fixed trigger disappearing from custom function node

cypress/e2e/pnp/testMultiplyObject.cy.ts, src/classes/NodeClass.tsx, src/nodes/draw/abstract.tsx, src/nodes/draw/draw.tsx
Fixes this bug - https://trello.com/c/146AVuwW/99-unexpected-warning-about-output-array-on-multiply-draw-node-when-clicking-one-of-the-outputs
* Fixed outputMultiplierInjected error
* Fixed outputs default values getting overridden on load
* Added test
=> Fix parsing warning on output

cypress/e2e/pnp/dialogs.cy.ts, cypress/e2e/pnp/helpers.ts, src/App.tsx, src/LeftsideContent.tsx, src/PPStorage.tsx, src/TestController.ts, src/components/Dialogs.tsx
* The graph name is now selected when opening the edit dialog to rename it
* Moved the edit and delete dialog out of App.tsx
* Fixed an issue with the graph name not being update when renaming
* Added dialog tests for edit, delete and a one for share. No tests yet
* for logging into github and sharing a gist
* for download a file
=> Refactor dialogs

cypress/e2e/pnp/dialogs.cy.ts, src/widgets.tsx
This update only targets the string type
* Clicking Enter will
* not create a line break anymore
* trigger executeOptimizedChain
* The value is still updated on change, but the trigger allows a node which is not updated on change, to be triggered via enter. We can remove this, but it made sense to me, at least in Øysteins use case.
* For line break you can do shift+enter
=> Update enter behaviour for textfield

src/widgets.tsx
* Fix code widget not updating in inspector when switching between the same node types
=> Fix code widget not updating in inspector when switching between the same node types

assets/examples/z test pivot, offset and rotation.ppgraph, src/nodes/draw/abstract.tsx, src/nodes/draw/draw.tsx, src/nodes/utility/utility.ts
* added a background and a margin to the DRAW_Base
* the default is transparent and 0, but it allows to
* easily add backgrounds and margins to any draw element like text, linegraph, combine, etc.
* the margin is currently a single value for all sides, but I would like to support different margins in the future
* fixed an issue with anchor point. now everything rotates, scales and offsets correctly
* updated the reroute node so it can be moved a bit more easily
* updated the pivot example graph
* removed skew left over
* added `executions` undefined check due to this bug which I was not able to fix - https://trello.com/c/0Krxd8m0
https://github.com/fakob/plug-and-play/assets/4619772/60f9fa8b-6826-4f0d-b29f-bdf1643fd3a9
=> Add margin and background to DRAW_Base
